anuket-project/RA2

doc/ref_arch/kubernetes/chapters/chapter02.rst
doc/ref_arch/kubernetes/chapters/chapter04.rst

Closes [#3354](https://github.com/anuket-project/anuket-specifications/issues/3354)
If needed, the long list of prerequisites is [here](https://github.com/intel/afxdp-plugins-for-kubernetes?tab=readme-ov-file#prerequisites).

[RA2 Ch2 Ch4] AF_XDP specs

---

doc/ref_arch/kubernetes/chapters/chapter01.rst
doc/ref_arch/kubernetes/chapters/chapter04.rst
doc/ref_arch/kubernetes/chapters/chapter06.rst
doc/ref_arch/kubernetes/refs.bib

fixes https://github.com/anuket-project/anuket-specifications/issues/3392

[RA2 Ch1] Change k8s rel to 129

---

doc/ref_arch/kubernetes/chapters/chapter02.rst
doc/ref_arch/kubernetes/chapters/chapter03.rst
doc/ref_arch/kubernetes/chapters/chapter04.rst
doc/ref_arch/kubernetes/refs.bib

fixes https://github.com/anuket-project/anuket-specifications/issues/3299

[RA2] add cert-manager

---

doc/ref_arch/kubernetes/chapters/chapter03.rst
doc/ref_arch/kubernetes/chapters/chapter04.rst
doc/ref_arch/kubernetes/refs.bib

Closes [#2823](https://github.com/anuket-project/anuket-specifications/issues/2823)

[Ch3, Ch4]: Adding PaaS requirements

---

doc/ref_arch/kubernetes/chapters/chapter03.rst

Fixes anuket-project/anuket-specifications#3410

[Ch3]: Fixing Table 3.3 in GSMA rendering

---

doc/ref_arch/kubernetes/chapters/chapter02.rst

Fixes anuket-project/anuket-specifications#1957

[Ch2]: Modify "Not Required" to "Optional"

---

doc/ref_arch/kubernetes/chapters/chapter01.rst

Fixes anuket-project/anuket-specifications#3374

[Ch1]: Restructure to follow the GSMA conventions

---

doc/ref_arch/kubernetes/chapters/chapter04.rst
doc/ref_arch/kubernetes/conf.py
doc/ref_arch/kubernetes/refs.bib
doc/ref_arch/kubernetes/test-requirements.txt
doc/ref_arch/kubernetes/tox.ini

Fixes anuket-project/anuket-specifications#3429

3429 change cnf wg to cnti

---

doc/ref_arch/kubernetes/chapters/chapter06.rst
doc/ref_arch/kubernetes/refs.bib

It adds all the beta and alpha Features defacto skipped in RC2.

[RA2][RC2] Update the Feature skip list

---

doc/ref_arch/kubernetes/chapters/chapter01.rst
doc/ref_arch/kubernetes/chapters/chapter02.rst
doc/ref_arch/kubernetes/chapters/chapter05.rst
doc/ref_arch/kubernetes/chapters/chapter07.rst

Based on Tier1, 2 and 3 of https://inclusivenaming.org/word-lists/
Fixes https://github.com/anuket-project/anuket-specifications/issues/2396

Implement inclusive naming

---

doc/ref_arch/kubernetes/chapters/chapter02.rst
doc/ref_arch/kubernetes/chapters/chapter04.rst

partly closes [#3447](https://github.com/anuket-project/anuket-specifications/issues/3447)

RA2 Ch2,4 vDU requirements

---

doc/ref_arch/kubernetes/chapters/chapter02.rst
doc/ref_arch/kubernetes/chapters/chapter03.rst
doc/ref_arch/kubernetes/chapters/chapter04.rst
doc/ref_arch/kubernetes/chapters/chapter07.rst
doc/ref_arch/kubernetes/conf.py
doc/ref_arch/kubernetes/refs.bib
doc/ref_arch/kubernetes/test-requirements.txt
doc/ref_arch/kubernetes/tox.ini

It backports the changes done during the proof reading

Backport to pieman

---

doc/ref_arch/kubernetes/chapters/chapter01.rst
doc/ref_arch/kubernetes/chapters/chapter03.rst
doc/ref_arch/kubernetes/chapters/chapter04.rst
doc/ref_arch/kubernetes/chapters/chapter06.rst
doc/ref_arch/kubernetes/refs.bib

fixes https://github.com/anuket-project/anuket-specifications/issues/3446
updated chapters 1,3,4,6

[RA2] update to k8s 1.31

---

doc/ref_arch/kubernetes/chapters/chapter04.rst
doc/ref_arch/kubernetes/refs.bib

fixes https://github.com/anuket-project/anuket-specifications/issues/2792
looking at RM chapter 9, there's no clear list of requirements. 
also this cannot have references to chapter 2, as there's no requirements on cluster lcm?

[RA2 Ch4] add section on caas manager

---

.github/workflows/review-docs.yml
.vale/config/vocabularies/Anuket/accept.txt

Fixes the missing dependency problem of Vale.
Adds Ceph as it was requested in https://github.com/anuket-project/RA2/pull/32/files#r1790147984

Installing Sphinx for Vale

---

doc/ref_arch/kubernetes/chapters/chapter02.rst

Fixes https://github.com/anuket-project/anuket-specifications/issues/2189

Rmoval of SFC requirement

---

doc/ref_arch/kubernetes/chapters/chapter04.rst

closes [#3457](https://github.com/anuket-project/anuket-specifications/issues/3457)

[RA2 Ch4] Proofreading and column width

---

doc/ref_arch/kubernetes/chapters/chapter05.rst
doc/ref_arch/kubernetes/chapters/chapter07.rst

fixes [#3458](https://github.com/anuket-project/anuket-specifications/issues/3458)

[ra2] proofread ch5 and ch7

---

doc/ref_arch/kubernetes/chapters/chapter02.rst
doc/ref_arch/kubernetes/chapters/chapter04.rst

fixes [#2707](https://github.com/anuket-project/anuket-specifications/issues/2707)

[RA2 CH2 CH4] add specs for storage replication and encryption

---

.vale/config/vocabularies/Anuket/accept.txt
doc/ref_arch/kubernetes/chapters/chapter02.rst
doc/ref_arch/kubernetes/chapters/chapter04.rst

fixes https://github.com/anuket-project/anuket-specifications/issues/2709

[RA2 Ch4] implement e.man specs

---

doc/ref_arch/kubernetes/chapters/chapter02.rst

fixes #2822
opening a new issue to implement inf.stg.02

[RA2 ch2] sync storage requirements with RM
